# SPDX-FileCopyrightText: 2021 Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0
# 
info:
  description: SIMAPP initial local configuration
  version: 1.0.0
  http-version: 1

logger:
  APP:
    ReportCaller: false
    debugLevel: info

configuration:
  http-protocol: "http"
  http-timeout: 1000
  max-time-interval: 35
  provision-network-slice: true # if enabled, Device Groups & Slices configure by simapp
  sub-provision-endpt:
    addr: localhost # subscriber configuation endpoint.
    port: 5000
  # sub-proxy-endpt: # used if subscriber proxy is enabled in the ROC.
  #   addr: subscriber-proxy.aether-roc.svc.cluster.local
  #   port: 5000

  # Configure Subscriber IMSIs and their security details.
  # You can have any number of subscriber ranges
  # This block is always necessary to establish range(s) of valid IMSIs
  subscribers:
  - ueId-start: "208930100007487"
    ueId-end: "208930100017487"
    # ueId-end: "208930100007500"
    plmnId: "20893"
    opc: "981d464c7c52eb6e5036234984ad0bcf"
    op: ""
    key: "5122250214c33e723a5dd523fc145fc0"
    sequenceNumber: "16f3b3f70fc2"
  # - ueId-start: "218930100017501"
  #   ueId-end: "218930100027586"
  #   plmnId: "20893"
  #   opc: "981d464c7c52eb6e5036234984ad0bcf"
  #   op: ""
  #   key: "5122250214c33e723a5dd523fc145fc0"
  #   sequenceNumber: "16f3b3f70fc2"
  # - ueId-start: "228930100017501"
  #   ueId-end: "228930100027586"
  #   plmnId: "20893"
  #   opc: "981d464c7c52eb6e5036234984ad0bcf"
  #   op: ""
  #   key: "5122250214c33e723a5dd523fc145fc0"
  #   sequenceNumber: "16f3b3f70fc2"
  # - ueId-start: "238930100017501"
  #   ueId-end: "238930100027586"
  #   plmnId: "20893"
  #   opc: "981d464c7c52eb6e5036234984ad0bcf"
  #   op: ""
  #   key: "5122250214c33e723a5dd523fc145fc0"
  #   sequenceNumber: "16f3b3f70fc2"
  # - ueId-start: "248930100017501"
  #   ueId-end: "248930100027586"
  #   plmnId: "20893"
  #   opc: "981d464c7c52eb6e5036234984ad0bcf"
  #   op: ""
  #   key: "5122250214c33e723a5dd523fc145fc0"
  #   sequenceNumber: "16f3b3f70fc2"

  # Configure Device Groups (ignored if provision-network-slice is disabled)
  device-groups:
  - name:  "gnbsim-user-group1"
    imsi-start: "208930100007487"
    imsi-end: "208930100017487"
    ip-domain-name: "pool1"
    ip-domain-expanded:
      dnn: internet
      dns-primary: "8.8.8.8"        # Value is sent to UE
      mtu: 1460                     # Value is sent to UE when PDU Session Established
      ue-ip-pool: "172.250.0.0/16"  # IP address pool for subscribers
      ue-dnn-qos:
        dnn-mbr-downlink: 1000      # UE level downlink QoS (Maximum bit rate per UE)
        dnn-mbr-uplink:   1000      # UE level uplink QoS (Maximum bit rate per UE)
        bitrate-unit: Mbps          # Unit for above QoS rates
        traffic-class:              # Default bearer QCI/ARP (not used in 5G)
          name: "platinum"
          qci: 9
          arp: 6
          pdb: 300
          pelr: 6
    site-info: "enterprise"
  # - name:  "gnbsim-user-group2"
  #   imsi-start: "218930100017501"
  #   imsi-end: "218930100027586"
  #   ip-domain-name: "pool1"
  #   ip-domain-expanded:
  #     dnn: internet
  #     dns-primary: "8.8.8.8"        # Value is sent to UE
  #     mtu: 1460                     # Value is sent to UE when PDU Session Established
  #     ue-ip-pool: "172.250.0.0/16"  # IP address pool for subscribers
  #     ue-dnn-qos:
  #       dnn-mbr-downlink: 1000      # UE level downlink QoS (Maximum bit rate per UE)
  #       dnn-mbr-uplink:   1000      # UE level uplink QoS (Maximum bit rate per UE)
  #       bitrate-unit: Mbps          # Unit for above QoS rates
  #       traffic-class:              # Default bearer QCI/ARP (not used in 5G)
  #         name: "platinum"
  #         qci: 9
  #         arp: 6
  #         pdb: 300
  #         pelr: 6
  #   site-info: "enterprise"
  # - name:  "gnbsim-user-group3"
  #   imsi-start: "228930100017501"
  #   imsi-end: "228930100027586"
  #   ip-domain-name: "pool1"
  #   ip-domain-expanded:
  #     dnn: internet
  #     dns-primary: "8.8.8.8"        # Value is sent to UE
  #     mtu: 1460                     # Value is sent to UE when PDU Session Established
  #     ue-ip-pool: "172.250.0.0/16"  # IP address pool for subscribers
  #     ue-dnn-qos:
  #       dnn-mbr-downlink: 1000      # UE level downlink QoS (Maximum bit rate per UE)
  #       dnn-mbr-uplink:   1000      # UE level uplink QoS (Maximum bit rate per UE)
  #       bitrate-unit: Mbps          # Unit for above QoS rates
  #       traffic-class:              # Default bearer QCI/ARP (not used in 5G)
  #         name: "platinum"
  #         qci: 9
  #         arp: 6
  #         pdb: 300
  #         pelr: 6
  #   site-info: "enterprise"
  # - name:  "gnbsim-user-group4"
  #   imsi-start: "238930100017501"
  #   imsi-end: "238930100027586"
  #   ip-domain-name: "pool1"
  #   ip-domain-expanded:
  #     dnn: internet
  #     dns-primary: "8.8.8.8"        # Value is sent to UE
  #     mtu: 1460                     # Value is sent to UE when PDU Session Established
  #     ue-ip-pool: "172.250.0.0/16"  # IP address pool for subscribers
  #     ue-dnn-qos:
  #       dnn-mbr-downlink: 1000      # UE level downlink QoS (Maximum bit rate per UE)
  #       dnn-mbr-uplink:   1000      # UE level uplink QoS (Maximum bit rate per UE)
  #       bitrate-unit: Mbps          # Unit for above QoS rates
  #       traffic-class:              # Default bearer QCI/ARP (not used in 5G)
  #         name: "platinum"
  #         qci: 9
  #         arp: 6
  #         pdb: 300
  #         pelr: 6
  #   site-info: "enterprise"
  # - name:  "gnbsim-user-group5"
  #   imsi-start: "248930100017501"
  #   imsi-end: "248930100027586"
  #   ip-domain-name: "pool1"
  #   ip-domain-expanded:
  #     dnn: internet
  #     dns-primary: "8.8.8.8"        # Value is sent to UE
  #     mtu: 1460                     # Value is sent to UE when PDU Session Established
  #     ue-ip-pool: "172.250.0.0/16"  # IP address pool for subscribers
  #     ue-dnn-qos:
  #       dnn-mbr-downlink: 1000      # UE level downlink QoS (Maximum bit rate per UE)
  #       dnn-mbr-uplink:   1000      # UE level uplink QoS (Maximum bit rate per UE)
  #       bitrate-unit: Mbps          # Unit for above QoS rates
  #       traffic-class:              # Default bearer QCI/ARP (not used in 5G)
  #         name: "platinum"
  #         qci: 9
  #         arp: 6
  #         pdb: 300
  #         pelr: 6
  #   site-info: "enterprise"
  # UPF allocates IP address if there is only 1 device-group
  # SMF allocates IP address if there is >1 device-group

  # Configure Network Slices (ignored if provision-network-slice is disabled)
  network-slices:
  - name: "default"      # can be any unique slice name
    slice-id:        # must match with slice configured in gNB, UE
      sd: "010203"
      sst: 1
    site-device-group:
    - "gnbsim-user-group1"   # All UEs in this device-group are assigned to this slice
    # - "gnbsim-user-group2"
    # - "gnbsim-user-group3"
    # - "gnbsim-user-group4"
    # - "gnbsim-user-group5"
    # Applicaiton filters control what each user can access.
    # Default, allow access to all applications
    application-filtering-rules:
    - rule-name: "ALLOW-ALL"
      priority: 250
      action: "permit"
      endpoint: "0.0.0.0/0"
      app-mbr-uplink: 1 #1Mbps
      app-mbr-downlink: 5 #5Mbps
      bitrate-unit: Mbps
      traffic-class : #if same as APN-AMBR then its default bearer rule
        name: "silver"
        qci: 9
        arp: 6
        pdb: 300
        pelr: 6
    site-info:
      # Provide gNBs and UPF details and also PLMN for the site
      gNodeBs:
      - name: "gnb1"
        tac: 1
      - name: "gnb2"
        tac: 2
      plmn:
        mcc: "208"
        mnc: "93"
      site-name: "enterprise"
      upf:
        upf-name: "upf"  # associated UPF for this slice. One UPF per Slice.
        upf-port: 8805